name: CI

on:
  pull_request:
    types: ['opened', 'synchronize']
    branches:
      - main
    paths:
      - 'backend/src/**'
      
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: set up TimeZone
        run: |
            sudo timedatectl set-timezone Asia/Seoul

      - name: Give permission for Gradle
        run: chmod +x backend/gradlew

      - name: Build with Gradle  
        run: |
          cd backend
          ./gradlew build
        
      - name: Write Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: Comment (Annotation) for Failed Test
        uses: mikepenz/action-junit-report@v3
        if: always()
        with: 
          report_paths: '**/build/test-results/test/TEST-*.xml'
