name: Deploy to production environment

on: 
  pull_request:
    types: ['closed']
    branches:
      - main
    # paths:
      # - 'backend/src/**'

permissions:
  contents: read

jobs:
  build-and-upload-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Give perssion for Gradle
        run: chmod +x backend/gradlew

      - name: Build with Gradle
        run: |
          cd backend
          ./gradlew build

      - name: Upload JAR file to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: BackendApplication
          path: backend/build/libs/*.jar
    
    
